Ras 136 update remote db structure
BeeCoders-Projects/restaurant-automation pull request #33
Opened 2023-06-07 18:32 UTC by DmytroTeliukov

2023-06-07 18:59 UTC, MaksymGolik requested changes

2023-06-07 18:59 UTC, MaksymGolik commented on src/main/java/com/beecoders/ras/model/entity/OrderDish.java
> +
Please add artificial id

2023-06-08 07:54 UTC, MaksymGolik approved these changes

2023-06-08 07:55 UTC, olena-syrotenko approved these changes

2023-06-08 08:25 UTC, merged